import type { NextPage } from 'next';
import React from 'react';
import Image from 'next/image';
import Divider from '@mui/material/Divider';
import divider from '../public/images/divider.svg';
import formula from '../public/images/formula.svg';
import seta from '../public/images/arrow.png';
import styles from '../styles/components/MaisInfos.module.css';
import Head from 'next/head';

import Layout from '../components/layouts/default';
import { Box, Grid, Stack, Typography } from '@mui/material';

const MaisInfosComponent: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Metodologia</title>
        <meta name="description" content="Generated by Facom-UFMS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack
        sx={{
          margin: '5%',
          display: 'grid',
          rowGap: '40px',
          justifyItems: 'center',
          color: 'primary.main',
        }}
      >
        {/* Modelo Estatístico */}
        <Box
          sx={{
            backgroundColor: 'primary.contrastText',
            borderRadius: '5px',
            boxShadow: '0 2px 3px rgba(0, 0, 0, 0.25)',
            width: '850px',
            height: '250px',
          }}
        >
          <Typography
            sx={{
              fontSize: '1.5em',
              fontWeight: 'bold',
              m: '7px',
              pl: '30px',
            }}
          >
            Entenda nosso modelo estatístico
          </Typography>
          <Divider sx={{ borderBottomWidth: '2.5px' }}></Divider>
          <Grid
            container
            direction="row"
            justifyContent="space-between"
            alignItems="center"
            mt="7px"
            p="0 37px"
          >
            <Grid item sx={{ width: '40%' }}>
              <Typography
                sx={{
                  fontSize: '1.2em',
                  fontWeight: 'bold',
                }}
              >
                Dados inseridos/Variáveis utilizadas
              </Typography>
              <Grid
                container
                wrap="nowrap"
                justifyContent="left"
                alignItems="center"
                sx={{ width: '60%' }}
              >
                <Typography
                  sx={{
                    fontSize: '1em',
                    fontStyle: 'italic',
                  }}
                >
                  Partos, Partos Normais, Partos Sensíveis, Internações Evitadas, Taxa de
                  Mortalidade Materna
                </Typography>
              </Grid>
            </Grid>

            <Grid item>
              <Image src={seta} alt="Seta" width={50} height={50} />
            </Grid>

            <Grid item>
              <Typography
                sx={{
                  fontSize: '1.2em',
                  fontWeight: 'bold',
                }}
              >
                Modelo de cálculo estatístico utilizado
              </Typography>
              <Stack>
                <a href="../uploads/Metodologia-PPSUS.pdf" target="_blank" rel="noreferrer">
                  <Typography
                    sx={{ fontStyle: 'italic', '&:hover': { textDecoration: 'underline' } }}
                  >
                    Acessar arquivo completo
                  </Typography>
                </a>
              </Stack>
            </Grid>
          </Grid>
        </Box>

        {/* Dados Coletados */}
        <Box
          sx={{
            backgroundColor: 'primary.contrastText',
            borderRadius: '5px',
            boxShadow: '0 2px 3px rgba(0, 0, 0, 0.25)',
            width: '850px',
            height: '250px',
          }}
        >
          <Typography
            sx={{
              fontSize: '1.5em',
              fontWeight: 'bold',
              m: '7px',
              pl: '30px',
            }}
          >
            De onde nossos dados são coletados
          </Typography>
          <Divider sx={{ borderBottomWidth: '2.5px' }} />
          <Grid
            container
            direction="row"
            justifyContent="space-between"
            alignItems="center"
            height="65%" // arrumar !!!
            mt="7px"
            p="0 37px"
          >
            <Grid item>
              <Grid sx={{ justifyContent: 'center', alignItems: 'center' }}>
                <Typography
                  sx={{
                    fontSize: '1.2em',
                    fontWeight: 'bold',
                  }}
                >
                  Portal da Transparência - Registro Civil
                </Typography>
                <Stack>
                  <a
                    href="https://transparencia.registrocivil.org.br/registros"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Typography
                      sx={{ fontStyle: 'italic', '&:hover': { textDecoration: 'underline' } }}
                    >
                      https://transparencia.registrocivil.org.br/registros
                    </Typography>
                  </a>
                </Stack>
                <Typography
                  sx={{
                    fontSize: '1.2em',
                    fontWeight: 'bold',
                  }}
                >
                  Portal da Transparência - Registro Civil
                </Typography>
                <Stack>
                  <a
                    href="https://transparencia.registrocivil.org.br/registros"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Typography
                      sx={{ fontStyle: 'italic', '&:hover': { textDecoration: 'underline' } }}
                    >
                      https://transparencia.registrocivil.org.br/registros
                    </Typography>
                  </a>
                </Stack>
              </Grid>
            </Grid>
            <Divider orientation="vertical" flexItem sx={{ borderRightWidth: 2.5 }} />
            <Grid item>
              <Typography
                sx={{
                  fontSize: '1.2em',
                  fontWeight: 'bold',
                }}
              >
                Portal da Transparência - Registro Civil
              </Typography>
              <Stack>
                <a
                  href="https://transparencia.registrocivil.org.br/registros"
                  target="_blank"
                  rel="noreferrer"
                >
                  <Typography
                    sx={{ fontStyle: 'italic', '&:hover': { textDecoration: 'underline' } }}
                  >
                    https://transparencia.registrocivil.org.br/registros
                  </Typography>
                </a>
              </Stack>
              <Typography
                sx={{
                  fontSize: '1.2em',
                  fontWeight: 'bold',
                }}
              >
                Portal da Transparência - Registro Civil
              </Typography>
              <Stack>
                <a
                  href="https://transparencia.registrocivil.org.br/registros"
                  target="_blank"
                  rel="noreferrer"
                >
                  <Typography
                    sx={{ fontStyle: 'italic', '&:hover': { textDecoration: 'underline' } }}
                  >
                    https://transparencia.registrocivil.org.br/registros
                  </Typography>
                </a>
              </Stack>
            </Grid>
          </Grid>
        </Box>
      </Stack>

      <div className={styles.maisinfos}>
        <div className={styles.container}>
          <h2>Entenda nosso modelo estatístico</h2>

          <Divider className={styles.divider} sx={{ borderBottomWidth: '3px' }}></Divider>

          <div className={styles.box_container}>
            <div className={styles.box}>
              <h3 className={styles.dados}>Dados inseridos/Variáveis utilizadas</h3>
              <h4>Partos, Partos Normais,</h4>
              <h4>Partos Sensíveis,</h4>
              <h4>Internações Evitadas,</h4>
              <h4>Taxa de Mortalidade</h4>
              <h4>Materna</h4>
            </div>

            <span className={styles.seta}>
              <Image src={seta} alt="Seta" width={50} height={50} />
            </span>

            <div className={styles.box}>
              <h3>Modelo de cálculo estatístico utilizado</h3>
              <span className={styles.formula}>
                <Image src={formula} alt="Fórmula" width={200} height={70} />
              </span>
              <a href="../Metodologia-PPSUS.pdf" target="_blank" rel="noopener noreferrer">
                Acessar arquivo completo
              </a>
            </div>
          </div>
        </div>

        <div className={styles.container}>
          <h2>Onde são coletados nossos dados</h2>

          <Divider sx={{ borderBottomWidth: '3px' }}></Divider>

          <div className={styles.box_container}>
            <div className={styles.box}>
              <h3>Portal da Transparência - Registro Civil</h3>
              <a href="https://transparencia.registrocivil.org.br/registros">
                <h4>https://transparencia.registrocivil.org.br/registros</h4>
              </a>
              <h3>Portal da Transparência - Registro Civil</h3>
              <a href="https://transparencia.registrocivil.org.br/registros">
                <h4>https://transparencia.registrocivil.org.br/registros</h4>
              </a>
            </div>

            <span className={styles.seta}>
              <Image src={divider} alt="Divisor" width={50} height={120} />
            </span>

            <div className={styles.box}>
              <h3>Portal da Transparência - Registro Civil</h3>
              <a href="https://transparencia.registrocivil.org.br/registros">
                <h4>https://transparencia.registrocivil.org.br/registros</h4>
              </a>
              <h3>Portal da Transparência - Registro Civil</h3>
              <a href="https://transparencia.registrocivil.org.br/registros">
                <h4>https://transparencia.registrocivil.org.br/registros</h4>
              </a>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default MaisInfosComponent;
